POST http://localhost:3000/api/v1/user/create
Content-Type: application/json

{
    "username" :"nina",
    "password" :"nina"
}
###
GET  http://localhost:3000/api/v1
###
GET  http://localhost:3000/api/v1/user